version: '3'
services:
  postgresSQL:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=BDAGA
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgadmin3:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8890:80"
    depends_on:
      - postgresSQL
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  odoo-db-data:
